from fastapi import APIRouter, HTTPException
from src.services.llm_service.retrieve_and_answer import QuestionAnswerChain, get_response
from src.definitions.query_request import QueryRequest
from typing import Optional

router = APIRouter()

# Initialize the QuestionAnswerChain instance
qa_chain = QuestionAnswerChain()


@router.post("/chat/chat_agent")
async def chat_agent(request: QueryRequest, memory: Optional[bool] = True):
    try:
        if memory:
            # Call the get_response method
            response = get_response(
                history=request.history,
                query=request.query,
                collection_name=request.collection_name,
                k=request.k,
                app=qa_chain
            )
            # Collect the response generated by the generator
            return {"chat_history": response}

        else:
            response = get_response(
                history=[],
                query=request.query,
                collection_name=request.collection_name,
                k=request.k,
                app=qa_chain
            )
            # Collect the response generated by the generator
            return {"chat_history": response}

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))